import type { Metadata } from "next";

import "./styles.css";

import { css } from "@/styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={css({
          maxWidth: "50em",
          margin: "{spacing.10} auto",
        })}
      >
        {children}
      </body>
    </html>
  );
}
