import type { Metadata } from "next";

import "./styles.css";
import "@/styled-system/styles.css";

import { Sidebar } from "@/components/Sidebar";
import { flex, grid } from "@/styled-system/patterns";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

import "@fontsource/ibm-plex-sans";
import "@fontsource/ibm-plex-mono";

import { css } from "@/styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
