import type { Metadata } from "next";

import "./styles.css";
import "@/styled-system/styles.css";

import { Sidebar } from "@/components/Sidebar";
import { flex, grid } from "@/styled-system/patterns";

import { css } from "@/styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={flex({
            margin: "{spacing.10} auto",
            width: "90dvw",
            justify: "center",
            pos: "relative",
            alignItems: "flex-start",
          })}
        >
          <div
            className={css({
              position: "sticky",
              top: "10",
              width: 200,
            })}
          >
            <Sidebar />
          </div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
